peer review changes
silverstripe-terraformers/turnstile-captcha pull request #13
Opened 2023-06-27 02:18 UTC by DevKCode

2023-06-28 04:22 UTC, blueo requested changes
nice update Dev, just a few more bits to tidy up now we're using guzzle and env vars

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        $secret_key = $this->_secretKey ?: Environment::getEnv('SS_TURNSTILE_SECRET_KEY');
please put these into a getSecretKey function

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        $curlOptions = [];
these curl options (Proxy/ssl) can all be removed now we have the httpclient class

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        $curlOptions[CURLOPT_RETURNTRANSFER] = true;
remove all the curl options

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +       }catch (Throwable $e) {
[nitpick] can we run the phpcs linter on this to tidy up spacing etc?

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +           if($e instanceof RequestException && $e->hasResponse()){
this is swallowing quite a few exceptions - instead I think we should add a general validation error if something happens here and log the message using the logger interface (see line 226). So remove this if check, add a validation error here (probably the same as on line 223) and log the error - then return false. (see https://docs.guzzlephp.org/en/stable/quickstart.html#exceptions for the exceptions this is missing)

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +                'Turnstile Captch Field validation failed as request was not successful.'
typo

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
>      public function setProxyServer($server)
these proxy and the verify ssl methods can be removed

2023-06-28 04:22 UTC, blueo commented on src/Http/HttpClient.php
> +  protected ?Client $client;
spacing here

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        $client = HttpClient::create()->getClient();
can you add the client class as a dependency instead - eg https://docs.silverstripe.org/en/5/developer_guides/extending/injector/#dependencies-and-properties as this makes it easier to change with config

2023-06-28 04:22 UTC, blueo commented on tests/TestTurnstileCaptchaField.php
> +        $turnstileCaptchField->setSiteKey(Environment::getEnv('SS_TURNSTILE_SITE_KEY'));
a test probably shouln't use env vars - you can use the testing keys or fake keys

2023-06-28 04:22 UTC, blueo commented on tests/TestTurnstileCaptchaField.php
> +        $this->assertEmpty($responseData['error-codes']);
can we add a test in here ensuring that the validation will pass with a successful response and fail on an unsuccessful one?

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        $secretKey = $this->_secretKey ? $this->_secretKey :  Environment::getEnv('SS_TURNSTILE_SECRET_KEY');
this should use a getSecretKey function

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +     * @config TurnstileCaptchaField.proxy_server
these properties (Proxy/ssl) can be removed as the client class is where that should happen

2023-06-28 04:22 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        return $this->_sitekey ? $this->_sitekey : Environment::getEnv('SS_TURNSTILE_SITE_KEY');
this should also have a config option (eg keep self::config()->site_key)

2023-06-28 04:37 UTC, blueo requested changes

2023-06-28 04:37 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        if ($response->getStatusCode() !== 200) {
the docs say to check the 'outcome' property of the response so I wouldn't rely on just the response code. They could use that to indicate you successfully submitted a response but with a failed 'outcome'

2023-06-28 04:38 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        if ($response->getStatusCode() !== 200) {
see https://developers.cloudflare.com/turnstile/get-started/server-side-validation/

2023-06-28 04:40 UTC, blueo commented on src/Forms/TurnstileCaptchaField.php
> +        if ($response->getStatusCode() !== 200) {
eg if I decode the body of the response when I use an invalid key I get:

![image](https://github.com/silverstripe-terraformers/turnstile-captcha/assets/948122/7e328f1e-b33e-4f3a-828c-a8b83b19b571)

2023-06-29 21:52 UTC, DevKCode commented on README.md
>  Terraformers\TurnstileCaptcha\Forms\TurnstileCaptchaField:
I added like this, let me know If this works 
`SilverStripe\Core\Injector\Injector:
    Terraformers\TurnstileCaptcha\Http\HttpClient:
        class: App\HttpClient`

2023-06-30 03:25 UTC, blueo approved these changes

2023-06-30 03:25 UTC, merged